# vi: set filetype=dockerfile:
FROM pritunl/archlinux:latest

ADD . /tmp/auto_arch

WORKDIR /tmp/auto_arch

RUN ./bootstrap/sudo.sh
RUN ./bootstrap/optimize_pacman_mirrorlist.sh
RUN ./bootstrap/upgrade_system.sh


{% for ps in provision_scripts %}
RUN ./software/{{ps}}
{% endfor %}


CMD ["uname", "-a"]
