#!/usr/bin/env ruby

target = ARGV[0]

# USAGE
# pkgs_install ./aur/*.pkgs
# pkgs_install ./software/haskell.pkgs

def expand_targets(target)
  "$(cat #{target})"
end

system("pacaur -S --noconfirm --noedit --needed #{expand_targets(target)}", out: $stdout, err: $stderr)
