# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "renegade_arch"

  # use a static ip for convenience
  # must be the same ip as the one you'll set in ~/.ssh/config
  config.vm.network :private_network, ip: "192.168.123.123"

#  config.vm.synced_folder "~/offline/", "/vagrant/offline"
#
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

end
