FROM archlinux:latest

# Setup
RUN pacman -S --noconfirm --needed base-devel ruby python-pip npm

# pkgs
RUN gem install $(cat ./lang_pkgs/ruby.gem)
RUN pip install $(cat ./lang_pkgs/python.pip)
RUN npm install $(cat ./lang_pkgs/node.npm)

CMD ["uname", "-a"]
