FROM archlinux:latest

# Setup
RUN pacman -S --noconfirm --needed systemd

# FIXME doesnt work
#RUN ./systemd/ntp.sh

RUN ./systemd/entropy.sh

RUN ./systemd/gdm.sh
# FIXME doesnt work cuz gdm is already thr
# RUN ./systemd/lightdm.sh

CMD ["uname", "-a"]
