FROM nfnty/arch-mini:latest

ADD . ~/auto_arch

WORKDIR ~/auto_arch

RUN ./sh/sudo.sh
RUN ./sh/optimize_pacman_mirrorlist.sh
RUN ./sh/upgrade_system.sh
RUN ./sh/create_user.sh testuser testpass
RUN pacman -S --noconfirm --needed base base-devel

CMD ["uname", "-a"]
